todo_app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register('notes', views.NotesViewSet, basename='notes')

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls')),
]

todo_app/todo_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
    path('api/', include('api.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

todo_app/user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('accounts/regiser/', views.RegisterView.as_view(), name='register')
]

todo_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    {% block extra_css %}

    {% endblock %}
</head>
<body>
{% block sidebar %}
    <nav class="sidebar">
        <div class="logo">Меню</div>
        <ul class="menu-items">
            <li class="menu-item">
                <a href="{% url 'index' %}">Заметки</a>
            </li>
            <li class="menu-item">
                <a href="{% url 'trash' %}">Корзина</a>
            </li>
            <li class="menu-item">
                <a href="{% url 'user:profile' %}">Профиль</a>
            </li>
            <li class="menu-item">
                <a href="{% url 'category' %}">Категории</a>
            </li>
        </ul>
    </nav>
{% endblock %}

<div class="main-content">
    <h1>{{ h1 }}</h1>

    {% block content %}

    {% endblock %}
</div>
</body>
</html>